### ISSUE TITLE
what is the actual value I am having in sherd Preferences  when user color

### ISSUE THREAD

**Issue by BMomani** [xdtianyu/ColorPicker#3]
I'm trying to make decision (change theme) based on user preferences

```

<org.xdty.preference.ColorPreference
        android:key="@string/pref_theme_key"
        android:title="Color Theme"
        android:summary="This is a color preference"
        tools:dialogTitle="@string/default_color"
        tools:colors="@array/default_rainbow"
        tools:columns="5"
        tools:material="true"
        android:defaultValue="@color/tomato"/>
```

and the code reseveing the value and make decision based in it

```
 int chosenTheme = _sharedPreferences.getInt( context.getString(R.string.pref_theme_key) , R.color.tomato);
            switch (chosenTheme) {
                case R.color.tomato:
                    return (R.style.AppTheme_NoActionBar_RedTheme);
                case R.color.peacock:
                    return (R.style.AppTheme_NoActionBar_BlueTheme);
            }
```

and I found the value saved in sherd preference file when choosing `R.color.tomato` is `-2818048` what is this value

**Comment by xdtianyu** [comment]
`R.color.tomato` is reference to  hexadecimal value `0xd50000`  
`<color name="tomato">#d50000</color>`
It's hexadecimal in decimal `(-2818048)10 = (FFFFFFFFFFD50000)16`, You can convert the value [here](http://www.binaryhexconverter.com/decimal-to-hex-converter)
